[build]
  command = "npm run build"
  publish = "build"

[dev]
  framework = "create-react-app"
  targetPort = 3000
  port = 8888
  functions = "netlify/functions"  # Path to your serverless functions

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
