const movieLanguages = [
  { name: "Arabic", originalCode: "ar", code: "ar-SA" },
  { name: "Bengali", originalCode: "bn", code: "bn-BD" },
  { name: "Bulgarian", originalCode: "bg", code: "bg-BG" },
  { name: "Chinese (Cantonese)", originalCode: "zh", code: "zh-HK" },
  { name: "Chinese (Mandarin)", originalCode: "zh", code: "zh-CN" },
  { name: "Croatian", originalCode: "hr", code: "hr-HR" },
  { name: "Czech", originalCode: "cs", code: "cs-CZ" },
  { name: "Danish", originalCode: "da", code: "da-DK" },
  { name: "Dutch", originalCode: "nl", code: "nl-NL" },
  { name: "English", originalCode: "en", code: "en-US" },
  { name: "Filipino", originalCode: "fil", code: "fil-PH" },
  { name: "Finnish", originalCode: "fi", code: "fi-FI" },
  { name: "French", originalCode: "fr", code: "fr-FR" },
  { name: "German", originalCode: "de", code: "de-DE" },
  { name: "Greek", originalCode: "el", code: "el-GR" },
  { name: "Hebrew", originalCode: "he", code: "he-IL" },
  { name: "Hindi", originalCode: "hi", code: "hi-IN" },
  { name: "Hungarian", originalCode: "hu", code: "hu-HU" },
  { name: "Indonesian", originalCode: "id", code: "id-ID" },
  { name: "Italian", originalCode: "it", code: "it-IT" },
  { name: "Japanese", originalCode: "ja", code: "ja-JP" },
  { name: "Malay", originalCode: "ms", code: "ms-MY" },
  { name: "Malayalam", originalCode: "ml", code: "ml-IN" },
  { name: "Norwegian", originalCode: "no", code: "no-NO" },
  { name: "Persian", originalCode: "fa", code: "fa-IR" },
  { name: "Polish", originalCode: "pl", code: "pl-PL" },
  { name: "Portuguese", originalCode: "pt", code: "pt-PT" },
  { name: "Punjabi", originalCode: "pa", code: "pa-IN" },
  { name: "Romanian", originalCode: "ro", code: "ro-RO" },
  { name: "Russian", originalCode: "ru", code: "ru-RU" },
  { name: "Serbian", originalCode: "sr", code: "sr-RS" },
  { name: "Slovak", originalCode: "sk", code: "sk-SK" },
  { name: "Slovenian", originalCode: "sl", code: "sl-SI" },
  { name: "Spanish", originalCode: "es", code: "es-ES" },
  { name: "Swedish", originalCode: "sv", code: "sv-SE" },
  { name: "Tamil", originalCode: "ta", code: "ta-IN" },
  { name: "Telugu", originalCode: "te", code: "te-IN" },
  { name: "Thai", originalCode: "th", code: "th-TH" },
  { name: "Turkish", originalCode: "tr", code: "tr-TR" },
  { name: "Ukrainian", originalCode: "uk", code: "uk-UA" },
  { name: "Urdu", originalCode: "ur", code: "ur-PK" },
  { name: "Vietnamese", originalCode: "vi", code: "vi-VN" },
];

export default movieLanguages;
